image: Visual Studio 2017

cache:
  - packages -> **\packages.config

configuration: Debug

build:
  parallel: true
  project: 

before_build:
  - nuget restore

environment:
  access_token: "UPDATE_ME"
